# Generated by Django 5.1.3 on 2025-03-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
