# Generated by Django 5.1.3 on 2025-02-11 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_project_collaborationrequest_collaboration'),
        ('users', '0002_profile_last_payment_profile_total_earnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.AlterField(
            model_name='content',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='users.profile'),
        ),
        migrations.CreateModel(
            name='Collaborate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('content_type', models.CharField(choices=[('short_film', 'Short Film'), ('podcast', 'Podcast'), ('documentary', 'Documentary'), ('entertainment', 'Entertainment Project')], max_length=50)),
                ('idea_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='CollaborationRequest',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
