# Generated by Django 5.1.3 on 2025-02-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_collaborationrequest_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cast',
            field=models.TextField(default='Not Mentioned'),
        ),
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
    ]
