# Generated by Django 5.1.3 on 2025-02-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cast',
            field=models.TextField(blank=True, default='Not Mentioned'),
        ),
        migrations.AlterField(
            model_name='content',
            name='country',
            field=models.CharField(blank=True, default='Not Mentioned', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, default='Not Mentioned', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(blank=True, default='Not Mentioned', max_length=200),
        ),
        migrations.DeleteModel(
            name='ContentImage',
        ),
    ]
