# Generated by Django 5.1.3 on 2025-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_content_cast_alter_content_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cast',
            field=models.TextField(default='Not Mentioned'),
        ),
        migrations.AlterField(
            model_name='content',
            name='country',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
    ]
